ids_for_detailed_info = ['JCFBRBSDWLSWU',
                         'ILQQRHM5VZL3I',
                         'V2TJPQ3EBICT2',
                         'IQS2SC3TNBISO',
                         'QDPDIHGD4E676',
                         'KIR3DLO6HPN5O',
                         'SEDDADB6IMJ4A',
                         'HCAICAKSMFT3I',
                         'MQIX2CPRH4REO',
                         'B5FBYXAG7SESQ',
                         '7SYJUCB7WIZNU',
                         'FQSSOXCVVFEKS',
                         'IF3R44I4RQNZ4',
                         'QANTUVRJHVETG',
                         'E4QUDMTGCVQ4W',
                         '73CVOXKOVCVKE',
                         'ZVZ7CI6W57WYK',
                         'UA4UUJF7K57KQ',
                         'DMDQU24U7VKWM',
                         'LMK4N4P263P24',
                         'MVOD63OMQ3EDQ',
                         'JLXEZ24O3NLJ2',
                         'JH6CSN47U2XFI',
                         'DMKKAFMZIX23W',
                         '7SNGXEJA7AF5I',
                         'OH7YI6PK5UWCQ',
                         'WC5LSQXSDUPIK',
                         'QSH4LKKN65Q2S',
                         'SKRIGJQOBX4UG',
                         'X73DQ4CY2DYJE',
                         '5VEHZW6WBITTW',
                         'TEA2LKXDASU6A',
                         '5FOLD5NZ652I6',
                         'YPFEM37RBFXIE',
                         'YVWH3NAAER5D4',
                         'GQGVHOSICKYOE',
                         'J2ABCDEOPNWQO',
                         'DJ2SP3BA45HHA',
                         'VIYTAOAY66MRC',
                         'DR67PV2HD5AVK',
                         '5BFFW2FOZUAG2',
                         'JREKFYCY2X42G',
                         'HXNAHSQH62CC6',
                         'CAYSEICOZSV3G',
                         'UUZWRPQG5OQVO',
                         'FF5D7F2JNEJF4',
                         'SWSBWCK7DDVFQ',
                         'M643OVFCAWGP4',
                         '2ZTTR2V37DOSM',
                         'PXSGIWK5LVBWQ',
                         'AD2CMXXDNJIY4',
                         'AF2JAZPD2JV62',
                         'PIIMD3N5VUOY4',
                         '7ZR7X4RBSAWQG',
                         '7ANEYA6OJGVB2',
                         'EVA4PYEVKGDBK',
                         'NROC5XYJXWBBS',
                         '4RWXOEBOREA4C',
                         '6SOGQNVJDGDMW',
                         'UUZS5ZJOFPZFE',
                         'POTIRUD4PKBOM',
                         'INHF2VORWZMTG',
                         'P2FLHWHGQSFL2']

# ids_for_detailed_info = ['JCFBRBSDWLSWU',
#                          'ILQQRHM5VZL3I',
#                          'V2TJPQ3EBICT2',]
                         # 'IQS2SC3TNBISO',
                         # 'QDPDIHGD4E676',
                         # 'KIR3DLO6HPN5O',
                         # 'SEDDADB6IMJ4A',
                         # 'HCAICAKSMFT3I',
                         # 'MQIX2CPRH4REO',
                         # 'B5FBYXAG7SESQ']
